// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3DR8NZITwZbP8tt2HrysSvAjYXBPra6c',
    appId: '1:639603288747:web:daf9e6dcc0f3bf6e3fe5ee',
    messagingSenderId: '639603288747',
    projectId: 'mind-point-99cb5',
    authDomain: 'mind-point-99cb5.firebaseapp.com',
    storageBucket: 'mind-point-99cb5.appspot.com',
    measurementId: 'G-53D7KPFYPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwN4RLNwIszuT9KxF8qPqz8Ob9ML8a918',
    appId: '1:639603288747:android:c77c257ccaefa7553fe5ee',
    messagingSenderId: '639603288747',
    projectId: 'mind-point-99cb5',
    storageBucket: 'mind-point-99cb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMvmsYU-0sUB0IRs2loQVWNvu5HFDxzE',
    appId: '1:639603288747:ios:8c7b07354dbd8cb33fe5ee',
    messagingSenderId: '639603288747',
    projectId: 'mind-point-99cb5',
    storageBucket: 'mind-point-99cb5.appspot.com',
    iosClientId: '639603288747-gosllq2dpua93lunm2ol7d7vg06gjjse.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSMvmsYU-0sUB0IRs2loQVWNvu5HFDxzE',
    appId: '1:639603288747:ios:8c7b07354dbd8cb33fe5ee',
    messagingSenderId: '639603288747',
    projectId: 'mind-point-99cb5',
    storageBucket: 'mind-point-99cb5.appspot.com',
    iosClientId: '639603288747-gosllq2dpua93lunm2ol7d7vg06gjjse.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindpoint',
  );
}
